//
// Created by Jack Noordhuis on 5/2/20.
//

#include <SFML/Config.hpp>

#include "config.h"

PHP_MINIT_FUNCTION(sfml_config){
    REGISTER_LONG_CONSTANT("SFML_VERSION_MAJOR", SFML_VERSION_MAJOR, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("SFML_VERSION_MINOR", SFML_VERSION_MINOR, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("SFML_VERSION_PATCH", SFML_VERSION_PATCH, CONST_CS | CONST_PERSISTENT);
}
